name: Question
description: Ask about anything related
labels: [ "Type: Question" ]
title: "[Question] add text here"
assignees: [ "CreativeCodeCat" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! :hugs:

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have clearly stated my question in English with a descriptive title."
          required: true
        - label: "I have searched the [open](https://github.com/DroidWorksStudio/mLauncher/issues) and [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) issues to ensure this question hasn’t already been answered."
          required: true
        - label: "I have read through the [WIKI](https://github.com/DroidWorksStudio/mLauncher/wiki) for existing documentation."
          required: true
        - label: "I have provided enough context and background for others to understand my question."
          required: true
        - label: "I understand that incomplete or vague questions may be closed without an answer."
          required: true
        - label: "I optionally [donated](https://www.buymeacoffee.com/CreativeCodeCat) to support the MultiLauncher mission."
          required: false

  - type: textarea
    id: what-is-the-question
    attributes:
      label: What is/are your question(s)?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include.

  - type: checkboxes
    id: checklist-accept
    attributes:
      label: "Terms and Conditions"
      options:
        - label: "I have read all the rules above and filled in the required fields to the best of my ability."
          required: true
        - label: "I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project."
          required: true
