name: Feature request
description: Suggest an idea for this project
labels: [ "Type: Enhancement" ]
title: "[Enhancement] add text here"
assignees: [ "CreativeCodeCat" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to make MultiLauncher better by suggesting a feature. :hugs:
        Your ideas are highly welcome!

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have written the feature request in English with a clear and descriptive title."
          required: true
        - label: "I confirmed there are **no existing feature requests** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - that already suggest this idea."
          required: true
        - label: "I have reviewed the [WIKI](https://github.com/DroidWorksStudio/mLauncher/wiki) to ensure the feature does not already exist."
          required: true
        - label: "I have checked the [latest GitHub release](https://github.com/DroidWorksStudio/mLauncher/releases) to confirm the feature hasn't already been added."
          required: true
        - label: "I verified this feature is not already mentioned in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md)."
          required: true
        - label: "I clearly explained the feature, its use case, and why it would benefit the project."
          required: true
        - label: "This submission includes only **one feature request**."
          required: true
        - label: "I understand that vague or poorly explained requests may be closed without further discussion."
          required: true
        - label: "I optionally [donated](https://www.buymeacoffee.com/CreativeCodeCat) to support the MultiLauncher mission."
          required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the app's look or behavior to change to suit your needs.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include.

  - type: checkboxes
    id: checklist-accept
    attributes:
      label: "Terms and Conditions"
      options:
        - label: "I have read all the rules above and filled in the requiered fields to the best of my ability."
          required: true
        - label: "I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project."
          required: true
