name: Feature request
description: Suggest an idea for this project
labels: ['Type: Enhancement']
title: '[Enhancement] add text here'
assignees: ['HeCodes2Much']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to make mLauncher better by suggesting a feature. :hugs:
        Your ideas are highly welcome!

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I will make sure to have the issue written in English with an English title."
          required: true
        - label: "I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to."
          required: true
        - label: "I have already checked the [WIKI](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist."
          required: true
        - label: "I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md)."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise."
          required: true
        - label: "This issue contains only one feature request."
          required: true
        - label: "I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission."
          required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the app's look or behavior to change to suit your needs.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include.

  - type: checkboxes
    id: checklist-accept
    attributes:
      label: "Terms and Conditions"
      options:
        - label: "I have read all the rules above and filled in the requiered fields to the best of my ability."
          required: true
        - label: "I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project."
          required: true
